name: Snowplow Micro examples with Cypress

on:

  push:
    branches:
      - develop

jobs:

  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: snowplow-micro-examples

      - name: Start Micro
        run: |
          cd $GITHUB_WORKSPACE/snowplow-micro-examples
          docker run --mount type=bind,source=$(pwd)/micro,destination=/config -p 9090:9090 snowplow/snowplow-micro:latest --collector-config /config/micro.conf --iglu /config/iglu.json &

      - name: Wait on port 9090
        run: while ! nc -z localhost 9090; do sleep 0.1; done

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          cd $GITHUB_WORKSPACE/snowplow-micro-examples
          if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi

      - name: Start Django server
        run: |
          cd $GITHUB_WORKSPACE/snowplow-micro-examples
          python app/manage.py runserver 8000 > /dev/null 2>&1 &

      - name: Wait on port 8000
        run: while ! nc -z localhost 8000; do sleep 0.1; done

      - name: Npm install
        run: |
          cd $GITHUB_WORKSPACE/snowplow-micro-examples
          npm install

      - name: cypress-run the specs
        run: |
          cd $GITHUB_WORKSPACE/snowplow-micro-examples
          npm run cypress:run -- --spec "cypress/integration/app-specs/*"
          npm run cypress:run -- --spec "cypress/integration/micro-specs/*"
