name: testing with Snowplow Micro

on:

  push:
    branches:
      - develop

jobs:

  testing:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: snowplow-micro-examples

      - name: Start Micro
        run: |
          cd $GITHUB_WORKSPACE/snowplow-micro-examples
          docker-compose up -d

      - name: Wait on port 9090
        run: while ! nc -z localhost 9090; do sleep 0.1; done

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          cd $GITHUB_WORKSPACE/snowplow-micro-examples
          if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi

      - name: Start Django server
        run: |
          cd $GITHUB_WORKSPACE/snowplow-micro-examples
          python app/manage.py runserver 8000 > /dev/null 2>&1 &

      - name: Wait on port 8000
        run: while ! nc -z localhost 8000; do sleep 0.1; done

      - name: Npm install
        run: |
          cd $GITHUB_WORKSPACE/snowplow-micro-examples
          npm install

      - name: Run Nightwatch tests
        run: |
          cd $GITHUB_WORKSPACE/snowplow-micro-examples
          npm test

      - name: Run Cypress tests
        run: |
          cd $GITHUB_WORKSPACE/snowplow-micro-examples
          npm run cypress:run

      - name: Sample running the pair-run npm script
        run: |
          cd $GITHUB_WORKSPACE/snowplow-micro-examples
          PAIR_PATTERN=02 npm run cy-micro:pair-run
