name: Snowplow Micro with Cypress

on:

  push:
    branches-ignore:
      - '**'

jobs:

  cypress-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: snowplow-micro-examples

      - name: Start Containers and wait on ports 9090 and 8000
        run: |
          cd $GITHUB_WORKSPACE/snowplow-micro-examples
          docker-compose up -d
          while ! nc -z localhost 9090; do sleep 0.1; done
          while ! nc -z localhost 8000; do sleep 0.1; done

      - name: Npm install
        run: |
          cd $GITHUB_WORKSPACE/snowplow-micro-examples
          npm install

      - name: Cypress-run the specs
        run: |
          cd $GITHUB_WORKSPACE/snowplow-micro-examples
          npm run cypress:run

      - name: Sample running the pair-run npm script
        run: |
          cd $GITHUB_WORKSPACE/snowplow-micro-examples
          PAIR_PATTERN=02 npm run cy-micro:pair-run
